[package]
name = "ansi2-wasm"
version = "0.1.1"
authors = ["ahaoboy <504595380@qq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
ansi2 = { path = "../ansi2" }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[profile.release]
opt-level = 3
