[package]
repository = "https://github.com/ahaoboy/ansi2"
name = "ansi2html"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "ansi2html"

[dependencies]
ansi2 = { version = "0.2", path = "../ansi2" }
html-escape= "0.2.13"
